SSD_Assignment/SSD_Assignment/Pages/Account/ManageUsers/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Account.ManageUsers
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DeleteModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.ApplicationUser.FindAsync(id);

            if (ApplicationUser != null)
            {
                _context.ApplicationUser.Remove(ApplicationUser);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Account/ManageUsers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Account.ManageUsers
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
       
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public EditModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);

            if (ApplicationUser == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ApplicationUser).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApplicationUserExists(ApplicationUser.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Audit/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;

namespace SSD_Assignment.Pages.Audit
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DetailsModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public AuditRecord AuditRecord { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AuditRecord = await _context.AuditRecords.SingleOrDefaultAsync(m => m.Audit_ID == id);

            if (AuditRecord == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Browse/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;

namespace SSD_Assignment.Pages.Browse
{
    public class DetailsModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DetailsModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Games Games { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Games = await _context.Games.SingleOrDefaultAsync(m => m.ID == id);

            if (Games == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Feedbacks/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SSD_Assignment.Data;
using SSD_Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Feedbacks
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public CreateModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            //throw new Exception("Test Error"); 
            return Page();
        }

        [BindProperty]
        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            //_context.Feedback.Add(Feedback);
            //await _context.SaveChangesAsync();   
            
            var userID = User.Identity.Name.ToString();
            Feedback.Username = userID;
            var feedback = new Feedback();
            Feedback.DateTimeStamp = DateTime.Now;

            _context.Feedback.Add(Feedback);

            //await _context.SaveChangesAsync();
            if (await _context.SaveChangesAsync() > 0)
            {
                // Create an auditrecord object                 
                var auditrecord = new AuditRecord();
                auditrecord.AuditActionType = "Add Feedback Record";
                auditrecord.DateTimeStamp = DateTime.Now;
                auditrecord.KeyfeedbackFieldID = Feedback.FeedbackID;

                // Get current logged-in use
                var user = User.Identity.Name.ToString();
                auditrecord.Username = user;

                _context.AuditRecords.Add(auditrecord);
                await _context.SaveChangesAsync();
            }


            return RedirectToPage("./Index");
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Feedbacks/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Feedbacks
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DeleteModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.SingleOrDefaultAsync(m => m.FeedbackID == id);

            if (Feedback == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.FindAsync(id);

            if (Feedback != null)
            {
                _context.Feedback.Remove(Feedback);
                //await _context.SaveChangesAsync();

                // Once a record is deleted, create an audit record                 
                if (await _context.SaveChangesAsync() > 0)
                {
                    var auditrecord = new AuditRecord();
                    auditrecord.AuditActionType = "Delete Feedback Record";
                    auditrecord.DateTimeStamp = DateTime.Now;
                    auditrecord.KeyfeedbackFieldID = Feedback.FeedbackID;

                    var userID = User.Identity.Name.ToString();
                    auditrecord.Username = userID;

                    _context.AuditRecords.Add(auditrecord);
                    await _context.SaveChangesAsync();
                }   
            }

            return RedirectToPage("./Index");
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Feedbacks/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Feedbacks
{
    public class DetailsModel : PageModel
    {
        
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DetailsModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Feedback Feedback { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Feedback = await _context.Feedback.SingleOrDefaultAsync(m => m.FeedbackID == id);

            if (Feedback == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Games/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;

namespace SSD_Assignment.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;

        public DetailsModel(SSD_Assignment.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public SSD_Assignment.Models.Games Games { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Games = await _context.Games.SingleOrDefaultAsync(m => m.ID == id);

            if (Games == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Roles/Manage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SSD_Assignment.Data;
using SSD_Assignment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace SSD_Assignment.Pages.Roles
{
    [Authorize(Roles = "Admin")]
    public class ManageModel : PageModel
    {
        private readonly SSD_Assignment.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        public ManageModel(SSD_Assignment.Data.ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public SelectList RolesSelectList;
        //contain a list of roles to populate select box
        public SelectList UsersSelectList;
        // contain a list of Users to populate select box
        public string selectedrolename { set; get; }
        public string selectedusername { set; get; }
        public string delrolename { set; get; }
        public string delusername { set; get; }
        public int usercountinrole { set; get; }
        public IList<ApplicationRole> Listroles { get; set; }
        public string ListUsersInRole(string rolename)
        {
            // Method - return a string showing a list of users based on specified role as parameter
            string strListUsersInRole = "";
            string roleid = _roleManager.Roles.SingleOrDefault(u => u.Name == rolename).Id;
            // Get no. of users for each specified role
            var count = _context.UserRoles.Where(u => u.RoleId == roleid).Count();
            usercountinrole = count;
            //Get a list of users for each specified role
            var listusers = _context.UserRoles.Where(u => u.RoleId == roleid);
            foreach (var oParam in listusers)
            { // loop thru each objects- get username based on userid and append to the returned string
                var userobj = _context.Users.SingleOrDefault(s => s.Id == oParam.UserId);
                strListUsersInRole += "[" + userobj.UserName + "] ";
            }
            return strListUsersInRole;
        }
        public async Task OnGetAsync()
        { //HTTPGet - when form is being loaded
          //get list of roles and users
            IQueryable<string> RoleQuery = from m in _roleManager.Roles orderby m.Name select m.Name;
            IQueryable<string> UsersQuery = from u in _context.Users orderby u.UserName select u.UserName;
            RolesSelectList = new SelectList(await RoleQuery.Distinct().ToListAsync());
            UsersSelectList = new SelectList(await UsersQuery.Distinct().ToListAsync());
            // Get all the roles
            var roles = from r in _roleManager.Roles
                        select r;
            Listroles = await roles.ToListAsync();
        }

        public async Task<IActionResult> OnPostAsync(string selectedusername, string selectedrolename)
        {
            //When the Assign button is pressed
            if ((selectedusername == null) || (selectedrolename == null))
            {
                return RedirectToPage("Manage");
            }
            ApplicationUser AppUser = _context.Users.SingleOrDefault(u => u.UserName == selectedusername);
            ApplicationRole AppRole = await _roleManager.FindByNameAsync(selectedrolename);

            IdentityResult roleResult = await _userManager.AddToRoleAsync(AppUser, AppRole.Name);
                if (roleResult.Succeeded)
                {
                    TempData["message"] = "Role added to this user successfully";
                    return RedirectToPage("Manage");

            }

            return RedirectToPage("Manage");
        }
        public async Task<IActionResult> OnPostDeleteUserRoleAsync(string delusername, string delrolename)
        {
            //When the Delete this user from Role button is pressed
            if ((delusername == null) || (delrolename == null))
            {
                return RedirectToPage("Manage");
            }
            ApplicationUser user = _context.Users.Where(u => u.UserName.Equals(delusername, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            if (await _userManager.IsInRoleAsync(user, delrolename))
            {
                await _userManager.RemoveFromRoleAsync(user, delrolename);
                TempData["message"] = "Role removed from this user successfully";
            }
            return RedirectToPage("Manage");
        }
    }
}

SSD_Assignment/SSD_Assignment/Pages/Roles/Create.cshtml
@page
@model SSD_Assignment.Pages.Roles.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Create a New Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Name" class="control-label"></label>
                <input asp-for="ApplicationRole.Name" class="form-control" />
                <span asp-validation-for="ApplicationRole.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Description" class="control-label"></label>
                <input asp-for="ApplicationRole.Description" class="form-control" />
                <span asp-validation-for="ApplicationRole.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSD_Assignment/SSD_Assignment/Pages/Roles/Delete.cshtml
@page
@model SSD_Assignment.Pages.Roles.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Description)
        </dd>

    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="ApplicationRole.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

SSD_Assignment/SSD_Assignment/Pages/Roles/Details.cshtml
@page
@model SSD_Assignment.Pages.Roles.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Name)
        </dd>
        <dt>
            Description
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.ApplicationRole.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

SSD_Assignment/SSD_Assignment/Pages/Roles/Edit.cshtml
@page
@model SSD_Assignment.Pages.Roles.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ApplicationRole.Id" />
            <div class="form-group">
                <label asp-for="ApplicationRole.Name" class="control-label"></label>
                <input asp-for="ApplicationRole.Name" class="form-control" />
                <span asp-validation-for="ApplicationRole.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Description" class="control-label"></label>
                <input asp-for="ApplicationRole.Description" class="form-control" />
                <span asp-validation-for="ApplicationRole.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.NormalizedName" class="control-label"></label>
                <input asp-for="ApplicationRole.NormalizedName" class="form-control" />
                <span asp-validation-for="ApplicationRole.NormalizedName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.ConcurrencyStamp" class="control-label"></label>
                <input asp-for="ApplicationRole.ConcurrencyStamp" class="form-control" />
                <span asp-validation-for="ApplicationRole.ConcurrencyStamp" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SSD_Assignment/SSD_Assignment/Pages/Roles/Index.cshtml
@page
@model SSD_Assignment.Pages.Roles.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationRole[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationRole[0].Description)
                </th>

        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ApplicationRole) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>

            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SSD_Assignment/SSD_Assignment/Pages/Roles/Manage.cshtml
@page
@model SSD_Assignment.Pages.Roles.ManageModel

@{
    ViewData["Title"] = "Manage";
}

<h2>Manage</h2>

<div class="row">
    <div class="col-md-4">
        <a asp-page="Create">[Create New Role]</a> |
        <a asp-page="Manage">[Manage User Roles]</a>
    </div>
</div>
@if (TempData["message"] != null)
{ <p><font color="red">@TempData["message"]</font></p>
}
<h3>[Role View - show the users in each role] </h3>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>Role Name </th>
            <th>Users assigned to this role</th>
            <th>No. of Users</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Listroles)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Name)</td>
                <td> @Model.ListUsersInRole(item.Name)</td>
                <td> @Model.usercountinrole </td>
            </tr>
        }
    </tbody>
</table>
<h3>[Add Role to User]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            @Html.Label("Select User : ") @Html.DropDownListFor(m => m.selectedusername, Model.UsersSelectList, "Select User", new { @class = "form-control" }) @Html.Label("Assign Role : ") @Html.DropDownListFor(m => m.selectedrolename, Model.RolesSelectList, "Select Role", new { @class = "form-control" })
            <br />
            <input type="submit" value="Assign" />
        </form>
    </div>
</div>
<hr />
<h3>[Delete A User from a Role]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            @Html.Label("Select User : ") @Html.DropDownListFor(m => m.delusername, Model.UsersSelectList, "Select User", new { @class = "form-control" }) @Html.Label("Select Role : ") @Html.DropDownListFor(m => m.delrolename, Model.RolesSelectList, "Select Role", new { @class = "form-control" })
            <br />
            <input type="submit" value="Delete this user from Role" asp-page-handler="DeleteUserRole" />
        </form>
    </div>
</div>